### ISSUE TITLE
A link in README.md is broken

### ISSUE THREAD

**Issue by AlexJameson** [errata-ai/vale-boilerplate#6]
Try the last link to documentation in the README.md file on line 52. The anchor is the following: `See the [documentation](https://errata-ai.gitbook.io/vale/configuration) for more information. `.

A possible substitution is the following: https://docs.errata.ai/vale/config

Here is the screenshot of the target page: 
![image](https://user-images.githubusercontent.com/33040934/146788180-270598be-28a9-44a7-91cc-2bfeeb95c8fc.png)

**Comment by jdkato** [comment]
Thanks, the links have been updated.
